### ISSUE TITLE
Have again the issue with last https://github.com/cilynx/rtl88x2bu/tree/5.6.1_30362.20181109_COEX20180928-6a6a

### ISSUE THREAD

**Issue by xMadNet** [PieGuy314/RTL88x2BU-RPi4-arm64-Driver-Patch#1]
Hi,
Config : RasPi 4B Rasbbian 64

I have no more the issue with this patch and previous Raspbian release :-)

**Since I went to last release :Linux XPiRasp4 5.10.4-v8+ #1389 SMP PREEMPT Wed Jan 6 13:52:18 GMT 2021 aarch64 GNU/Linux I have again the same isue (despite I patch manually the MakeFile with Makefile.patch (it was already almost good)) 

=>make ARCH=arm64 CROSS_COMPILE= -C /lib/modules/5.10.4-v8+/build M=/home/pi/wifidrivers/rtl88x2bu  modules
make[1]: Entering directory '/root/linux-684bc6681ac06b318b1ac02fbf7c8b0a61ee72e7'
......
ERROR: modpost: "__const_udelay" [/home/pi/wifidrivers/rtl88x2bu/88x2bu.ko] undefined!
ERROR: modpost: "__arch_copy_from_user" [/home/pi/wifidrivers/rtl88x2bu/88x2bu.ko] undefined!
ERROR: modpost: "_raw_spin_unlock" [/home/pi/wifidrivers/rtl88x2bu/88x2bu.ko] undefined!
ERROR: modpost: "__rcu_read_lock" [/home/pi/wifidrivers/rtl88x2bu/88x2bu.ko] undefined!
ERROR: modpost: "__rcu_read_unlock" [/home/pi/wifidrivers/rtl88x2bu/88x2bu.ko] undefined!
ERROR: modpost: "cpu_hwcap_keys" [/home/pi/wifidrivers/rtl88x2bu/88x2bu.ko] undefined!
ERROR: modpost: "csum_ipv6_magic" [/home/pi/wifidrivers/rtl88x2bu/88x2bu.ko] undefined!
ERROR: modpost: "__warn_printk" [/home/pi/wifidrivers/rtl88x2bu/88x2bu.ko] undefined!
ERROR: modpost: "arm64_const_caps_ready" [/home/pi/wifidrivers/rtl88x2bu/88x2bu.ko] undefined!
ERROR: modpost: "__udelay" [/home/pi/wifidrivers/rtl88x2bu/88x2bu.ko] undefined!
ERROR: modpost: "preempt_schedule_notrace" [/home/pi/wifidrivers/rtl88x2bu/88x2bu.ko] undefined!
ERROR: modpost: "__arch_copy_to_user" [/home/pi/wifidrivers/rtl88x2bu/88x2bu.ko] undefined!

** If I re compile the previous working code I have
=>make ARCH=arm64 CROSS_COMPILE= -C /lib/modules/5.10.4-v8+/build M=/home/pi/wifidrivers/rtl88x2bu.sav  modules
make[1]: Entering directory '/root/linux-684bc6681ac06b318b1ac02fbf7c8b0a61ee72e7'
  CC [M]  /home/pi/wifidrivers/rtl88x2bu.sav/core/rtw_cmd.o
In file included from /home/pi/wifidrivers/rtl88x2bu.sav/include/drv_types.h:79,
                 from /home/pi/wifidrivers/rtl88x2bu.sav/core/rtw_cmd.c:17:
/home/pi/wifidrivers/rtl88x2bu.sav/include/rtw_security.h:252:8: error: redefinition of ‘struct sha256_state’
 struct sha256_state {
        ^~~~~~~~~~~~
In file included from ./include/linux/filter.h:24,
                 from ./include/net/sock.h:59,
                 from ./include/linux/tcp.h:19,
                 from ./include/linux/ipv6.h:88,
                 from ./include/net/addrconf.h:50,
                 from /home/pi/wifidrivers/rtl88x2bu.sav/include/osdep_service_linux.h:48,
                 from /home/pi/wifidrivers/rtl88x2bu.sav/include/osdep_service.h:50,
                 from /home/pi/wifidrivers/rtl88x2bu.sav/include/drv_types.h:27,
                 from /home/pi/wifidrivers/rtl88x2bu.sav/core/rtw_cmd.c:17:
./include/crypto/sha.h:84:8: note: originally defined here
 struct sha256_state {
        ^~~~~~~~~~~~

Any workaround ?
Regards

**Comment by PieGuy314** [comment]
Sorry for the late reply. This is a kernel related issue. Raspbian (PiOS) 64-bit support for external drivers is, shall we say, in development. The 32-bit support across multiple releases is fine. I suffered the same problem and decided that life would be calmer sticking to 32-bit for the time being.
